### ISSUE TITLE
Hw 02 Ready For Grading

### ISSUE THREAD

**Issue by nicolehawe** [nicolehawe/STAT545-HW-Hawe-Nicole#3]
@vincenzocoia @gvdr @ksedivyhaley @joeybernhardt @mynamedaike @pgonzaleze  @derekcho

**Comment by diermc** [comment]
Hi Nicole, 

Off the bat, I would recommend including the links to all your homework files in your issue above to make it really easy to access from this window. That said you have everything located beautifully in a hw02 folder so that is great!

I would also include more details on your workflow and progress in your readme file, but I found them later in your assignment so all good. This assignment was a big step up, I have worked a lot with R but I was googling quite a lot. 

Your use of %>% and + is correct, if you want more clarification this is one of the [links](https://stackoverflow.com/questions/25179457/r-what-are-operators-like-in-called-and-how-can-i-learn-about-them) I used to read up on the difference a little. Basically, with %>% you are piping in and + you are kindof layering (overly simplified but that's the gist of how I remember it)

Generally, your assignment is solid and hits all the main points! Nice addition of colour in your figure. It's also great how you embedded the helpful links that you found, I did this in my assignment as well. Great work exploring a little into the 'doing more' section by tackling the first question listed. Your answers are really clear and well laid out. Maybe you can get some ideas on how to do the others when you peer-review this week.

Great job! :) 
-Sarah

**Comment by gbraich** [comment]
Hi Nicole,

Thanks for a nicely organized repo and a link to the md file in the README.

The comments provided in your workflow where very helpful, not only answering the questions of the assignment but also explaining what you did and why. While it was helpful to see the individual type of variables, this information is also provided with the structure function.

It was nice to see a variety of plots presented and also that you embedded your links whenever you relied on another source.  It was good to see you use piping, filter, select and other functions we've been learning in class including summarize, arrange, desc etc.  I also thought including colours using the aes function in ggplot showed good work.  It would have been useful in some cases to have more complex plots or to plot the results of your dplyr function like you did for Cambodia.  For example, the average life expectancies you found for Switzerland, Sweden and Norway would have been nice have visualized.

Nice job on explaining the extra work assignment and showing two possible solutions! 

Great effort

-Ginni

**Comment by ksedivyhaley** [comment]
**Smell test of data:** Yes, note concerns re: use of `typeof()`
**Explores at least one categorical/quantitative variable:** Yes, note concerns re: use of year
**Uses various plot types:** Histogram (base), scatter/line plots (ggplot)
**Uses `filter()`, `select()`, and `%>%`:** Yes
**Bonus (evaluate code, tables, more dplyr):** Partial: that's the correct code, but why? Also, `group_by()`, `summarize()`, and `arrange()`
**Reflection on process:** Yes

**Comments:**

- You're correct that this was a bigger assignment than HW01, which is mostly supposed to get students used to using GitHub, RStudio, and Rmarkdown.
- `typeof()` produces odd results with factors – it's calling `$country` and `$continent` integers because they are stored as integers under the hood, but it's important to be able to distinguish that from actual numeric data like `$lifeExp`. The `class()` function will tell you when something is a factor.
- "Year" is kind of a weird choice for categorical variable since it also has some numeric properties. Using a more typical categorical variable, like country or continent, could have produced a greater variety of plots.
- `select()` doesn't really do anything when you then pipe the results into ggplot. It's more of a function to use when you're making a table and don't want all the columns.
- Your ordering is functional, but not stylish. As a rule of thumb, you can generally start with your dataset and then pipe. For example,


``` r
ggplot(gapminder %>% 
         filter(country == "Canada"), aes(x = year, y = lifeExp)) + geom_line() + geom_point()
```

should be:

``` r
gapminder %>% 
       filter(country == "Canada") %>%
	ggplot(aes(x = year, y = lifeExp)) + 
		geom_line() +
		geom_point()
```
- Note also when using ggplot, it's good style to put every new layer (`+`) on a new line.
- You expressed a bit of confusion over `%>%` vs `+`. If you're adding a layer to a ggplot, you use `+`. Otherwise, pipe. I don't think you should ever need to pipe inside a ggplot if your pipe ordering uses the correct style as above.
- Good commentary – makes it easy to read the assignment.

Your mark will be distributed later. If you would like more feedback, please feel free to message me on slack.
